/*
 * FlashCanvas Pro
 *
 * Copyright (c) 2009      Tim Cameron Ryan
 * Copyright (c) 2009-2011 Shinya Muramatsu
 */
window.ActiveXObject&&!window.CanvasRenderingContext2D&&function(j,l){function k(j){return function(){return this[j]}}function Q(a){this.code=a;this.message=ga[a]}function B(a,b,c){if(!c){c=[];for(var d=0,f=a*b*4;d<f;++d)c[d]=0}this.width=a;this.height=b;this.data=c}function ha(a){this.width=a}function R(a){this.id=a.I++}function C(a){this.P=a;this.id=a.I++}function D(a,b){this.canvas=a;this.B=b;this.f=a.uniqueID;this.J();this.I=0;this.A="";this.c=0}function G(){if(l.readyState==="complete"){l.detachEvent(S,G);for(var a=l.getElementsByTagName(w),
b=0,c=a.length;b<c;++b)H.initElement(a[b])}}function T(){var a=event.srcElement,b=a.parentNode;a.blur();b.focus()}function I(){event.button&2&&event.srcElement.parentNode.setCapture()}function J(){event.button&2&&event.srcElement.parentNode.releaseCapture()}function U(){var a=event.propertyName;if(a==="width"||a==="height"){var b=event.srcElement,c=b[a],d=parseInt(c,10);if(isNaN(d)||d<0)d=a==="width"?300:150;if(c===d){b.style[a]=d+"px";b.getContext("2d").Q(b.width,b.height)}else b[a]=d}}function V(){j.detachEvent(W,
V);for(var a in p){var b=p[a],c=b.firstChild,d;for(d in c)if(typeof c[d]==="function")c[d]=m;for(d in b)if(typeof b[d]==="function")b[d]=m;c.detachEvent(X,T);c.detachEvent(K,I);b.detachEvent(L,J);b.detachEvent(Y,U)}j[Z]=m;j[$]=m;j[aa]=m;j[M]=m;j[ba]=m}function ia(){var a=l.getElementsByTagName("script");a=a[a.length-1];return l.documentMode>=8?a.src:a.getAttribute("src",4)}function ja(a){return a.toLowerCase()}function h(a){throw new Q(a);}function ca(a){var b=parseInt(a.width,10),c=parseInt(a.height,
10);if(isNaN(b)||b<0)b=300;if(isNaN(c)||c<0)c=150;a.width=b;a.height=c}var m=null,w="canvas",Z="CanvasRenderingContext2D",$="CanvasGradient",aa="CanvasPattern",M="FlashCanvas",ba="G_vmlCanvasManager",X="onfocus",K="onmousedown",L="onmouseup",Y="onpropertychange",S="onreadystatechange",W="onunload",t;try{t=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").match(/[\d,]+/)[0].replace(/,/g,".")}catch(ka){t=0}var u=j[M+"Options"]||{},da=u.swfPath||ia().replace(/[^\/]+$/,""),
z;z=parseInt(t)>9?da+"flash10canvas.swf":da+"flash9canvas.swf";var E={},F={},ea={},N={},x={},fa={},p={},A={},q=true,n={D:"turbo"in u?u.turbo:1,C:u.delay||0,M:u.disableContextMenu||0,N:u.imageCacheSize||100,F:u.usePolicyFile||0};if(t==="10.1.53.64"){n.D=0;n.C=30}D.prototype={save:function(){q||this.g(15);this.L.push([this.l,this.m,this.v,this.k,this.p,this.n,this.o,this.q,this.t,this.u,this.r,this.s,this.j,this.w,this.z]);this.a.push("B")},restore:function(){var a=this.L;if(a.length){a=a.pop();this.globalAlpha=
a[0];this.globalCompositeOperation=a[1];this.strokeStyle=a[2];this.fillStyle=a[3];this.lineWidth=a[4];this.lineCap=a[5];this.lineJoin=a[6];this.miterLimit=a[7];this.shadowOffsetX=a[8];this.shadowOffsetY=a[9];this.shadowBlur=a[10];this.shadowColor=a[11];this.font=a[12];this.textAlign=a[13];this.textBaseline=a[14]}this.a.push("C")},scale:function(a,b){this.a.push("D",a,b)},rotate:function(a){this.a.push("E",a)},translate:function(a,b){this.a.push("F",a,b)},transform:function(a,b,c,d,f,g){this.a.push("G",
a,b,c,d,f,g)},setTransform:function(a,b,c,d,f,g){this.a.push("H",a,b,c,d,f,g)},U:k("l"),ha:function(a){if(!isNaN(a)&&0<=a&&a<=1)this.a.push("I",this.l=a)},V:k("m"),ia:function(a){if(a==="source-atop"||a==="source-in"||a==="source-out"||a==="source-over"||a==="destination-atop"||a==="destination-in"||a==="destination-out"||a==="destination-over"||a==="lighter"||a==="darker"||a==="copy"||a==="xor")this.a.push("J",this.m=a)},da:k("v"),ra:function(a){var b=this.a;if(typeof a==="object")a=a.id;else(""+
a).indexOf("%")>0&&this.e.push(b.length+1);b.push("K",this.v=a)},S:k("k"),ga:function(a){var b=this.a;if(typeof a==="object")a=a.id;else(""+a).indexOf("%")>0&&this.e.push(b.length+1);b.push("L",this.k=a)},createLinearGradient:function(a,b,c,d){isFinite(a)&&isFinite(b)&&isFinite(c)&&isFinite(d)||h(9);this.a.push("M",a,b,c,d);return new C(this)},createRadialGradient:function(a,b,c,d,f,g){isFinite(a)&&isFinite(b)&&isFinite(c)&&isFinite(d)&&isFinite(f)&&isFinite(g)||h(9);if(c<0||g<0)h(1);this.a.push("N",
a,b,c,d,f,g);return new C(this)},createPattern:function(a,b){a||h(17);var c=a.tagName,d,f,g,e=this.f;if(c){c=c.toLowerCase();if(c==="img")d=a.getAttribute("src",2);else if(c===w){f=this.H(a);g=a!==this.canvas}else if(c==="video")return;else h(17)}else if(a.src)d=a.src;else h(17);b==="repeat"||b==="no-repeat"||b==="repeat-x"||b==="repeat-y"||b===""||b===m||h(12);if(!f){f=F[e][d];if(g=f===void 0)f=this.G(d)}this.a.push("O",f,b);if(g&&E[e]){this.i();++x[e]}return new R(this)},Y:k("p"),la:function(a){if(isFinite(a)&&
a>0)this.a.push("P",this.p=a)},W:k("n"),ja:function(a){if(a==="butt"||a==="round"||a==="square")this.a.push("Q",this.n=a)},X:k("o"),ka:function(a){if(a==="bevel"||a==="round"||a==="miter")this.a.push("R",this.o=a)},Z:k("q"),ma:function(a){if(isFinite(a)&&a>0)this.a.push("S",this.q=a)},ba:k("t"),pa:function(a){if(isFinite(a))this.a.push("T",this.t=a)},ca:k("u"),qa:function(a){if(isFinite(a))this.a.push("U",this.u=a)},$:k("r"),na:function(a){if(isFinite(a)&&a>=0)this.a.push("V",this.r=a)},aa:k("s"),
oa:function(a){var b=this.a;(""+a).indexOf("%")>0&&this.e.push(b.length+1);b.push("W",this.s=a)},clearRect:function(a,b,c,d){this.a.push("X",a,b,c,d);this.b||this.d();this.c=0},fillRect:function(a,b,c,d){q||this.g(1);this.a.push("Y",a,b,c,d);this.b||this.d();this.c=0},strokeRect:function(a,b,c,d){q||this.g(6);this.a.push("Z",a,b,c,d);this.b||this.d();this.c=0},beginPath:function(){this.a.push("a")},closePath:function(){this.a.push("b")},moveTo:function(a,b){this.a.push("c",a,b)},lineTo:function(a,
b){this.a.push("d",a,b)},quadraticCurveTo:function(a,b,c,d){this.a.push("e",a,b,c,d)},bezierCurveTo:function(a,b,c,d,f,g){this.a.push("f",a,b,c,d,f,g)},arcTo:function(a,b,c,d,f){f<0&&isFinite(f)&&h(1);this.a.push("g",a,b,c,d,f)},rect:function(a,b,c,d){this.a.push("h",a,b,c,d)},arc:function(a,b,c,d,f,g){c<0&&isFinite(c)&&h(1);this.a.push("i",a,b,c,d,f,g?1:0)},fill:function(){q||this.g(1);this.a.push("j");this.b||this.d();this.c=0},stroke:function(){q||this.g(6);this.a.push("k");this.b||this.d();this.c=
0},clip:function(){this.a.push("l")},isPointInPath:function(a,b){this.a.push("m",a,b);return this.i()==="true"},T:k("j"),O:function(a){var b=this.a,c=A[this.f].offsetHeight;this.h.push(b.length+2);b.push("o",c,this.j=a)},ea:k("w"),sa:function(a){var b=this.a;if(a==="start"||a==="end"||a==="left"||a==="right"||a==="center"){if(this.A!==this.canvas.currentStyle.direction)b.push("1",this.A=this.canvas.currentStyle.direction);b.push("p",this.w=a)}},fa:k("z"),ta:function(a){if(a==="top"||a==="hanging"||
a==="middle"||a==="alphabetic"||a==="ideographic"||a==="bottom")this.a.push("q",this.z=a)},fillText:function(a,b,c,d){q||this.g(9);this.h.push(this.a.length+1);this.a.push("r",a,b,c,d===void 0?Infinity:d);this.b||this.d();this.c=0},strokeText:function(a,b,c,d){q||this.g(10);this.h.push(this.a.length+1);this.a.push("s",a,b,c,d===void 0?Infinity:d);this.b||this.d();this.c=0},measureText:function(a){var b=A[this.f];try{b.style.font=this.font}catch(c){}b.innerText=a.replace(/[ \n\f\r]/g,"\t");return new ha(b.offsetWidth)},
drawImage:function(a,b,c,d,f,g,e,i,r){a||h(17);var o=a.tagName,v,s,O,y=arguments.length,P=this.f;if(o){o=o.toLowerCase();if(o==="img")v=a.getAttribute("src",2);else if(o===w){s=this.H(a);O=a!==this.canvas}else if(o==="video")return;else h(17)}else if(a.src)v=a.src;else h(17);if(!s){s=F[P][v];if(O=s===void 0)s=this.G(v)}q||this.g(0);if(y===3)this.a.push("u",y,s,b,c);else if(y===5)this.a.push("u",y,s,b,c,d,f);else if(y===9){if(d===0||f===0)h(1);this.a.push("u",y,s,b,c,d,f,g,e,i,r)}else return;if(O&&
E[P]){this.i();++x[P]}else this.b||this.d();this.c=0},createImageData:function(a,b){var c=Math.ceil;if(arguments.length===2){isFinite(a)&&isFinite(b)||h(9);if(a===0||b===0)h(1)}else{a instanceof B||h(9);b=a.height;a=a.width}a=c(a<0?-a:a);b=c(b<0?-b:b);return new B(a,b)},getImageData:function(a,b,c,d){isFinite(a)&&isFinite(b)&&isFinite(c)&&isFinite(d)||h(9);if(c===0||d===0)h(1);this.a.push("w",a,b,c,d);a=this.i();c=typeof JSON==="object"?JSON.parse(a):l.documentMode?eval(a):a.slice(1,-1).split(",");
a=c.shift();b=c.shift();return new B(a,b,c)},putImageData:function(a,b,c,d,f,g,e){a instanceof B||h(17);isFinite(b)&&isFinite(c)||h(9);var i=arguments.length,r=a.width,o=a.height,v=a.data;if(i===3)this.a.push("x",i,r,o,v.toString(),b,c);else if(i===7){isFinite(d)&&isFinite(f)&&isFinite(g)&&isFinite(e)||h(9);this.a.push("x",i,r,o,v.toString(),b,c,d,f,g,e)}this.b||this.d();this.c=0},J:function(){this.globalAlpha=this.l=1;this.globalCompositeOperation=this.m="source-over";this.fillStyle=this.k=this.strokeStyle=
this.v="#000000";this.lineWidth=this.p=1;this.lineCap=this.n="butt";this.lineJoin=this.o="miter";this.miterLimit=this.q=10;this.shadowBlur=this.r=this.shadowOffsetY=this.u=this.shadowOffsetX=this.t=0;this.shadowColor=this.s="rgba(0, 0, 0, 0.0)";this.font=this.j="10px sans-serif";this.textAlign=this.w="start";this.textBaseline=this.z="alphabetic";this.a=[];this.L=[];this.e=[];this.h=[];this.b=m;this.K=1},g:function(a){var b=this.a,c;if(this.l!==this.globalAlpha)b.push("I",this.l=this.globalAlpha);
if(this.m!==this.globalCompositeOperation)b.push("J",this.m=this.globalCompositeOperation);if(this.t!==this.shadowOffsetX)b.push("T",this.t=this.shadowOffsetX);if(this.u!==this.shadowOffsetY)b.push("U",this.u=this.shadowOffsetY);if(this.r!==this.shadowBlur)b.push("V",this.r=this.shadowBlur);if(this.s!==this.shadowColor){c=this.s=this.shadowColor;(""+c).indexOf("%")>0&&this.e.push(b.length+1);b.push("W",c)}if(a&1)if(this.k!==this.fillStyle){c=this.k=this.fillStyle;if(typeof c==="object")c=c.id;else(""+
c).indexOf("%")>0&&this.e.push(b.length+1);b.push("L",c)}if(a&2)if(this.v!==this.strokeStyle){c=this.v=this.strokeStyle;if(typeof c==="object")c=c.id;else(""+c).indexOf("%")>0&&this.e.push(b.length+1);b.push("K",c)}if(a&4){if(this.p!==this.lineWidth)b.push("P",this.p=this.lineWidth);if(this.n!==this.lineCap)b.push("Q",this.n=this.lineCap);if(this.o!==this.lineJoin)b.push("R",this.o=this.lineJoin);if(this.q!==this.miterLimit)b.push("S",this.q=this.miterLimit)}if(a&8){if(this.j!==this.font){a=A[this.f].offsetHeight;
this.h.push(b.length+2);b.push("o",a,this.j=this.font)}if(this.w!==this.textAlign)b.push("p",this.w=this.textAlign);if(this.z!==this.textBaseline)b.push("q",this.z=this.textBaseline);if(this.A!==this.canvas.currentStyle.direction)b.push("1",this.A=this.canvas.currentStyle.direction)}},d:function(){var a=this;a.b=setTimeout(function(){if(x[a.f])a.d();else{a.b=m;a.i(n.D)}},n.C)},R:function(){clearTimeout(this.b);this.b=m},i:function(a){var b,c,d,f=this.e,g=this.h,e=this.a,i=this.B;if(e.length){this.b&&
this.R();if(a){b=0;for(c=f.length;b<c;++b){d=f[b];e[d]=encodeURI(e[d])}b=0;for(c=g.length;b<c;++b){d=g[b];e[d]=encodeURIComponent(e[d])}}else{b=0;for(c=g.length;b<c;++b){d=g[b];e[d]=(""+e[d]).replace(/&/g,"&amp;").replace(/</g,"&lt;")}}b=e.join("\u0001");this.a=[];this.e=[];this.h=[];if(a){i.flashvars="c="+b;i.width=i.clientWidth+this.K;this.K^=-2}else return i.CallFunction('<invoke name="executeCommand" returntype="javascript"><arguments><string>'+b+"</string></arguments></invoke>")}},Q:function(a,
b){this.i();this.J();if(a>0)this.B.width=a;if(b>0)this.B.height=b;this.a.push("2",a,b);this.b||this.d();this.c=0},H:function(a){var b=a.uniqueID,c=w+":"+b;if(a.width===0||a.height===0)h(11);if(b!==this.f){a=p[b].getContext("2d");if(!a.c){b=++fa[b];c+=":"+b;a.a.push("3",b);a.b||a.d();a.c=1}}return c},G:function(a){var b=this.f,c=F[b],d=ea[b],f=c[a]=N[b]++;if(f>=n.N-1)N[b]=0;f in d&&delete c[d[f]];this.h.push(this.a.length+2);this.a.push("5",f,a);d[f]=a;return f}};C.prototype={addColorStop:function(a,
b){if(isNaN(a)||a<0||a>1)h(1);var c=this.P,d=this.id;(""+b).indexOf("%")>0&&c.e.push(c.a.length+3);c.a.push("y",d,a,b)}};Q.prototype=Error();var ga={1:"INDEX_SIZE_ERR",9:"NOT_SUPPORTED_ERR",11:"INVALID_STATE_ERR",12:"SYNTAX_ERR",17:"TYPE_MISMATCH_ERR",18:"SECURITY_ERR"},H={initElement:function(a){if(a.getContext)return a;var b=a.uniqueID,c="external"+b;E[b]=0;F[b]={};ea[b]=[];N[b]=0;x[b]=1;fa[b]=0;ca(a);a.innerHTML='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="'+location.protocol+
'//fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="100%" height="100%" id="'+c+'"><param name="allowScriptAccess" value="always"><param name="flashvars" value="id='+c+'"><param name="wmode" value="transparent"></object><span style="margin:0;padding:0;border:0;display:inline-block;position:static;height:1em;overflow:visible;white-space:nowrap"></span>';p[b]=a;var d=a.firstChild;A[b]=a.lastChild;var f=l.body.contains;if(f(a))d.movie=z;else var g=setInterval(function(){if(f(a)){clearInterval(g);
d.movie=z}},0);if(l.compatMode==="BackCompat"||!j.XMLHttpRequest)A[b].style.overflow="hidden";var e,i;if(q&&Object.defineProperty){e=l.createElement();b=new D(a,d);for(i in b)e[i]=b[i];b={globalAlpha:[e.U,e.ha],globalCompositeOperation:[e.V,e.ia],strokeStyle:[e.da,e.ra],fillStyle:[e.S,e.ga],lineWidth:[e.Y,e.la],lineCap:[e.W,e.ja],lineJoin:[e.X,e.ka],miterLimit:[e.Z,e.ma],shadowOffsetX:[e.ba,e.pa],shadowOffsetY:[e.ca,e.qa],shadowBlur:[e.$,e.na],shadowColor:[e.aa,e.oa],font:[e.T,e.O],textAlign:[e.ea,
e.sa],textBaseline:[e.fa,e.ta]};for(i in b){c=b[i];Object.defineProperty(e,i,{get:c[0],set:c[1],configurable:true})}}else{e=new D(a,d);q=0}e.O(e.j);a.getContext=function(r){return r==="2d"?e:m};a.toDataURL=function(r,o){if(a.width===0||a.height===0)return"data:,";(""+r).replace(/[A-Z]+/g,ja)==="image/jpeg"?e.a.push("A",r,typeof o==="number"?o:""):e.a.push("A",r);return e.i().slice(1,-1)};d.attachEvent(X,T);if(n.M){d.attachEvent(K,I);a.attachEvent(L,J)}n.F&&e.a.push("4","usePolicyFile",n.F);return a},
saveImage:function(a){a.firstChild.saveImage()},setOptions:function(a){for(var b in a){var c=a[b];switch(b){case "turbo":n.D=c;break;case "delay":n.C=c;break;case "disableContextMenu":var d=n.M=c;c=void 0;for(c in p){var f=p[c],g=d?"attachEvent":"detachEvent";f.firstChild[g](K,I);f[g](L,J)}break;case "imageCacheSize":n.N=c;break;case "usePolicyFile":d=b;c=n.F=c?1:0;f=void 0;for(f in p){g=p[f].getContext("2d");g.h.push(g.a.length+2);g.a.push("4",d,c)}}}},trigger:function(a,b){p[a].fireEvent("on"+b)},
unlock:function(a,b){x[a]&&--x[a];if(b){var c=p[a],d=c.firstChild,f,g;ca(c);f=c.width;g=c.height;c.style.width=f+"px";c.style.height=g+"px";if(f>0)d.width=f;if(g>0)d.height=g;d.resize(f,g);c.attachEvent(Y,U);E[a]=1}}};l.createElement(w);l.createStyleSheet().cssText=w+"{display:inline-block;overflow:hidden;width:300px;height:150px}";l.readyState==="complete"?G():l.attachEvent(S,G);j.attachEvent(W,V);if(z.indexOf(location.protocol+"//"+location.host+"/")===0){t=new ActiveXObject("Microsoft.XMLHTTP");
t.open("GET",z,false);t.send(m)}j[Z]=D;j[$]=C;j[aa]=R;j[M]=H;j[ba]={init:function(){},init_:function(){},initElement:H.initElement}}(window,document);